### ISSUE TITLE
Support `List[Optional[str]]` for example

### ISSUE THREAD

**Issue by PrettyWood** [Kludex/no-optional#10]
Hi @Kludex!
I actually used your lib on our code base before using another script to change `Union` into `|`.
Thanks for that! ❤️ 
But I had to do some manual changes since things like `List[Optional[str]]`, `Dict[str, Optional[str]]`, ... are currently ignored.
I don't know if it's something you want to work on and I'm sorry I don't have time to do it myself.
Cheers

**Comment by Kludex** [comment]
Ofc, I'll work on it tomorrow. 😁

I didn't notice that case. Thanks! 🙏

Btw, was it bothersome to use the libcst CLI instead of having a native one?

**Comment by Kludex** [comment]
The implementation became even simpler after this fix.

This was fixed on https://github.com/Kludex/no-optional/pull/11/.

Thanks for the report @PrettyWood ! :)

This is available on `no-optional` 0.2.0.

**Comment by PrettyWood** [comment]
You rock! 🚀 Thank you so much

> Btw, was it bothersome to use the libcst CLI instead of having a native one?

Not at all!

Btw I haven't seen any tool to migrate most typings to native 3.10 ones (maybe I didn't search well). This library could probably be enhanced or part of a bigger one!

**Comment by Kludex** [comment]
Maybe `pyupgrade`? https://github.com/asottile/pyupgrade#pep-604-typing-rewrites

Is something missing there?

**Comment by PrettyWood** [comment]
🤦 indeed thanks

**Comment by Kludex** [comment]
> 🤦 indeed thanks

No problem. Happy to help! 🙌
