### ISSUE TITLE
document why not to use an alternative tool

### ISSUE THREAD

**Issue by graingert** [Kludex/no-optional#17]
eg pyupgrade already does this and uses `T | None` on python 3.7 with `__future__.annotations`

I think the reasoning is runtime introspection doesn't support it and the feature flag might be removed in the future?

**Comment by Kludex** [comment]
> I think the reasoning is runtime introspection doesn't support it and the feature flag might be removed in the future?

Yes. It's a very limited package. 😅 

I'll document that later. Thanks Thomas. :)

**Comment by Kludex** [comment]
Closed by https://github.com/Kludex/no-optional/pull/22
