### ISSUE TITLE
README do not explain why you created this tool

### ISSUE THREAD

**Issue by raphaelauv** [Kludex/no-optional#6]
Hey,

could you add some context to the readme explaining why 

Union[ ... , None] is better than Optional[...]

Thanks :+1:

**Comment by Kludex** [comment]
sure, PR welcome. 👀

**Comment by raphaelauv** [comment]
I was not clear , It's a question , I don't know the answer

**Comment by Kludex** [comment]
Ah, sure. I'll add later on. This package is based on this tweet: https://twitter.com/tiangolo/status/1531583406651363328

Thanks 🙏

**Comment by Kludex** [comment]
done, ty @raphaelauv
